tasks:
  - name: Npm initialisation
    init: |
      npm install
      npm install nodemon mongoose
    command: npm run start
  - name: Run ReactApp
    init: |
      cd albums
      npm install
    command:  npm start
